name: Compile Sketch

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Compile sketch
        uses: arduino/compile-sketches@d7af6619a62e765d91f0a4d65b40cf061537a15d #v1
        with:
          fqbn: "STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C6,opt=osstd"
          platforms: |
            - name: STMicroelectronics:stm32
              source-url: https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
          libraries: |
            - name: FlexWire
          sketch-paths: |
            - SW/audi_volume_fix_stm32
