name: Compile Sketch

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "stm32duino:STM32F1:genericSTM32F103C"
          platforms: |
            - name: stm32duino:STM32F1
              source-url: https://raw.githubusercontent.com/rogerclarkmelbourne/Arduino_STM32/master/package_STM32duino_index.json
          libraries: |
            - name: FlexWire
          sketch-paths: |
            - SW/audi_volume_fix_stm32
